name: Build Binary

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.22.5' ]
        os-flavor: [ 'linux' ]
        architecture: [ 'amd64', 'arm', 'arm64' ]
        path-to-build: [ './cmd/email-random' ]

    steps:
      - uses: actions/checkout@v4
      # Caching is enabled by default when using setup-go
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      # You can test your matrix by printing the current Go version
      - name: Display Go version
        run: go version
      - name: Get dependencies
        run: go get ./...
      - name: Print the list of files
        run: ls -lsh .
      - name: Print command used to build binaries
        run: |
          echo GOOS=${{ matrix.os-flavor }} GOARCH=${{ matrix.architecture }} go build -o $(basename ${{ matrix.path-to-build }})-${{ matrix.os-flavor }}-${{ matrix.architecture }} ${{ matrix.path-to-build }}
